### ISSUE TITLE
How do I plot the architecture diagram of CAERNET?

### ISSUE THREAD

**Issue by girish332** [ndkhanh360/CAER#1]
I want to plot the architecture diagram of CAERnet can you please help me in doing so? I am unable to figure out what input dimensions should be passed for the model right now I am using this:

model1 = CAERSNet(context=True,context_attention=True,fusion_attention=True)

h1 = hl.build_graph(model1,torch.Tensor(1,3,224,224))
##hl is hiddenlayer library 

The error I am getting is this 

face_size, context_size = face.shape[2], context.shape[2]
AttributeError: 'NoneType' object has no attribute 'shape'

PLease help
 thank you

**Comment by ndkhanh360** [comment]
CAERSNet takes two tensors as input:
- face: shape (batch_size, 3, 96, 96)
- context: shape (batch_size, 3, 112, 112)

Example:
face, context = torch.rand(32, 3, 96, 96), torch.rand(32, 3, 112, 112)
model = CAERSNet()
output = model(face, context)

You can use Tensorboard to visualize the model graph!

Hope this helps.

**Comment by ndkhanh360** [comment]
You may find this useful: 
- Download the file **caer_architecture.zip** and unzip it. 
- Move into the **caer_architecture** folder, open the terminal (and install tensorboard if you haven't) then type
`tensorboard --logdir .`


[caer_architecture.zip](https://github.com/ndkhanh360/CAER/files/4830771/caer_architecture.zip)

**Comment by girish332** [comment]
Thank you so much sir
