### ISSUE TITLE
About the hyperparameter settings of the original paper 

### ISSUE THREAD

**Issue by TheKOne** [ndkhanh360/CAER#11]
Hello, do you know the hyperparameter settings of the original paper?

**Comment by ndkhanh360** [comment]
Thank you for your interest and patient. Unfortunately, this project is not maintained and developed anymore.
Instead, please check out our method which improves upon the CAER model [here](https://arxiv.org/abs/2111.04129).  A part of our source code can be accessed [here](https://github.com/minhnhatvt/glamor-net).
