### ISSUE TITLE
could you share the res of your implementation?

### ISSUE THREAD

**Issue by ssxxx1a** [ndkhanh360/CAER#3]
thanks a lot of your implementation, I'm having some problems about the res of caer , so could you please share your res in this implementation?

**Comment by ndkhanh360** [comment]
Thank you for your interest and patient. Unfortunately, this project is not maintained and developed anymore.
Instead, please check out our method which improves upon the CAER model [here](https://arxiv.org/abs/2111.04129). A part of our source code can be accessed [here](https://github.com/minhnhatvt/glamor-net/issues).
